# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = ./

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = ./

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start $(CMAKE_SOURCE_DIR)/CMakeFiles $(CMAKE_SOURCE_DIR)//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start $(CMAKE_SOURCE_DIR)/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_assert

# Build rule for target.
test_assert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_assert
.PHONY : test_assert

# fast build rule for target.
test_assert/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/build
.PHONY : test_assert/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/flash.dir/build.make CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named distclean

# Build rule for target.
distclean: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distclean
.PHONY : distclean

# fast build rule for target.
distclean/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distclean.dir/build.make CMakeFiles/distclean.dir/build
.PHONY : distclean/fast

#=============================================================================
# Target rules for targets named cppcheck

# Build rule for target.
cppcheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppcheck
.PHONY : cppcheck

# fast build rule for target.
cppcheck/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppcheck.dir/build.make CMakeFiles/cppcheck.dir/build
.PHONY : cppcheck/fast

#=============================================================================
# Target rules for targets named size

# Build rule for target.
size: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 size
.PHONY : size

# fast build rule for target.
size/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/build
.PHONY : size/fast

#=============================================================================
# Target rules for targets named addr2line

# Build rule for target.
addr2line: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 addr2line
.PHONY : addr2line

# fast build rule for target.
addr2line/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/addr2line.dir/build.make CMakeFiles/addr2line.dir/build
.PHONY : addr2line/fast

#=============================================================================
# Target rules for targets named symbols

# Build rule for target.
symbols: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 symbols
.PHONY : symbols

# fast build rule for target.
symbols/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/symbols.dir/build.make CMakeFiles/symbols.dir/build
.PHONY : symbols/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

external/printf/printf.o: external/printf/printf.c.o
.PHONY : external/printf/printf.o

# target to build an object file
external/printf/printf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/external/printf/printf.c.o
.PHONY : external/printf/printf.c.o

external/printf/printf.i: external/printf/printf.c.i
.PHONY : external/printf/printf.i

# target to preprocess a source file
external/printf/printf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/external/printf/printf.c.i
.PHONY : external/printf/printf.c.i

external/printf/printf.s: external/printf/printf.c.s
.PHONY : external/printf/printf.s

# target to generate assembly for a file
external/printf/printf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/external/printf/printf.c.s
.PHONY : external/printf/printf.c.s

src/common/assert_handler.o: src/common/assert_handler.c.o
.PHONY : src/common/assert_handler.o

# target to build an object file
src/common/assert_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/assert_handler.c.o
.PHONY : src/common/assert_handler.c.o

src/common/assert_handler.i: src/common/assert_handler.c.i
.PHONY : src/common/assert_handler.i

# target to preprocess a source file
src/common/assert_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/assert_handler.c.i
.PHONY : src/common/assert_handler.c.i

src/common/assert_handler.s: src/common/assert_handler.c.s
.PHONY : src/common/assert_handler.s

# target to generate assembly for a file
src/common/assert_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/assert_handler.c.s
.PHONY : src/common/assert_handler.c.s

src/common/ring_buffer.o: src/common/ring_buffer.c.o
.PHONY : src/common/ring_buffer.o

# target to build an object file
src/common/ring_buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/ring_buffer.c.o
.PHONY : src/common/ring_buffer.c.o

src/common/ring_buffer.i: src/common/ring_buffer.c.i
.PHONY : src/common/ring_buffer.i

# target to preprocess a source file
src/common/ring_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/ring_buffer.c.i
.PHONY : src/common/ring_buffer.c.i

src/common/ring_buffer.s: src/common/ring_buffer.c.s
.PHONY : src/common/ring_buffer.s

# target to generate assembly for a file
src/common/ring_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/ring_buffer.c.s
.PHONY : src/common/ring_buffer.c.s

src/common/trace.o: src/common/trace.c.o
.PHONY : src/common/trace.o

# target to build an object file
src/common/trace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/trace.c.o
.PHONY : src/common/trace.c.o

src/common/trace.i: src/common/trace.c.i
.PHONY : src/common/trace.i

# target to preprocess a source file
src/common/trace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/trace.c.i
.PHONY : src/common/trace.c.i

src/common/trace.s: src/common/trace.c.s
.PHONY : src/common/trace.s

# target to generate assembly for a file
src/common/trace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/common/trace.c.s
.PHONY : src/common/trace.c.s

src/drivers/io.o: src/drivers/io.c.o
.PHONY : src/drivers/io.o

# target to build an object file
src/drivers/io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/io.c.o
.PHONY : src/drivers/io.c.o

src/drivers/io.i: src/drivers/io.c.i
.PHONY : src/drivers/io.i

# target to preprocess a source file
src/drivers/io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/io.c.i
.PHONY : src/drivers/io.c.i

src/drivers/io.s: src/drivers/io.c.s
.PHONY : src/drivers/io.s

# target to generate assembly for a file
src/drivers/io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/io.c.s
.PHONY : src/drivers/io.c.s

src/drivers/led.o: src/drivers/led.c.o
.PHONY : src/drivers/led.o

# target to build an object file
src/drivers/led.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/led.c.o
.PHONY : src/drivers/led.c.o

src/drivers/led.i: src/drivers/led.c.i
.PHONY : src/drivers/led.i

# target to preprocess a source file
src/drivers/led.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/led.c.i
.PHONY : src/drivers/led.c.i

src/drivers/led.s: src/drivers/led.c.s
.PHONY : src/drivers/led.s

# target to generate assembly for a file
src/drivers/led.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/led.c.s
.PHONY : src/drivers/led.c.s

src/drivers/mcu_init.o: src/drivers/mcu_init.c.o
.PHONY : src/drivers/mcu_init.o

# target to build an object file
src/drivers/mcu_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/mcu_init.c.o
.PHONY : src/drivers/mcu_init.c.o

src/drivers/mcu_init.i: src/drivers/mcu_init.c.i
.PHONY : src/drivers/mcu_init.i

# target to preprocess a source file
src/drivers/mcu_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/mcu_init.c.i
.PHONY : src/drivers/mcu_init.c.i

src/drivers/mcu_init.s: src/drivers/mcu_init.c.s
.PHONY : src/drivers/mcu_init.s

# target to generate assembly for a file
src/drivers/mcu_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/mcu_init.c.s
.PHONY : src/drivers/mcu_init.c.s

src/drivers/uart.o: src/drivers/uart.c.o
.PHONY : src/drivers/uart.o

# target to build an object file
src/drivers/uart.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/uart.c.o
.PHONY : src/drivers/uart.c.o

src/drivers/uart.i: src/drivers/uart.c.i
.PHONY : src/drivers/uart.i

# target to preprocess a source file
src/drivers/uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/uart.c.i
.PHONY : src/drivers/uart.c.i

src/drivers/uart.s: src/drivers/uart.c.s
.PHONY : src/drivers/uart.s

# target to generate assembly for a file
src/drivers/uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/drivers/uart.c.s
.PHONY : src/drivers/uart.c.s

src/test/test.o: src/test/test.c.o
.PHONY : src/test/test.o

# target to build an object file
src/test/test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/test/test.c.o
.PHONY : src/test/test.c.o

src/test/test.i: src/test/test.c.i
.PHONY : src/test/test.i

# target to preprocess a source file
src/test/test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/test/test.c.i
.PHONY : src/test/test.c.i

src/test/test.s: src/test/test.c.s
.PHONY : src/test/test.s

# target to generate assembly for a file
src/test/test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_assert.dir/build.make CMakeFiles/test_assert.dir/src/test/test.c.s
.PHONY : src/test/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... addr2line"
	@echo "... cppcheck"
	@echo "... distclean"
	@echo "... flash"
	@echo "... format"
	@echo "... size"
	@echo "... symbols"
	@echo "... test_assert"
	@echo "... external/printf/printf.o"
	@echo "... external/printf/printf.i"
	@echo "... external/printf/printf.s"
	@echo "... src/common/assert_handler.o"
	@echo "... src/common/assert_handler.i"
	@echo "... src/common/assert_handler.s"
	@echo "... src/common/ring_buffer.o"
	@echo "... src/common/ring_buffer.i"
	@echo "... src/common/ring_buffer.s"
	@echo "... src/common/trace.o"
	@echo "... src/common/trace.i"
	@echo "... src/common/trace.s"
	@echo "... src/drivers/io.o"
	@echo "... src/drivers/io.i"
	@echo "... src/drivers/io.s"
	@echo "... src/drivers/led.o"
	@echo "... src/drivers/led.i"
	@echo "... src/drivers/led.s"
	@echo "... src/drivers/mcu_init.o"
	@echo "... src/drivers/mcu_init.i"
	@echo "... src/drivers/mcu_init.s"
	@echo "... src/drivers/uart.o"
	@echo "... src/drivers/uart.i"
	@echo "... src/drivers/uart.s"
	@echo "... src/test/test.o"
	@echo "... src/test/test.i"
	@echo "... src/test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

