on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: jiwonj05/msp430-gcc-9.3.1.11:latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - run: cmake --version
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make cppcheck HW=LAUNCHPAD
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=LAUNCHPAD
      - run: TOOLS_PATH=/home/ubuntu/dev/tools make HW=SBOT
      - run: TOOLS_PATH=/home/ubuntu/dev/tools ./tools/build_tests.sh
